# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'T.E.C.H.' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for T.E.C.H.

  target 'T.E.C.H.Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'T.E.C.H.UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
